## Import Numpy

In [1]:
import numpy as np

## Create Numpy array

### Create Numpy arrays from Python lists or elements

###### One-dimensional array 

In [2]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array((4.3, 3.2, 2.1, 9.8))
arr2

array([4.3, 3.2, 2.1, 9.8])

##### Two-dimensional array

In [4]:
arr = np.array([[9, 21, 53],[45, 12, 43], [54, 21, 11]])
arr

array([[ 9, 21, 53],
       [45, 12, 43],
       [54, 21, 11]])

##### Three-dimensional array

In [5]:
arr = np.array((((1, 2), (7, 8)), ((9, 10), (11,12))))
arr

array([[[ 1,  2],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

##### Derived data types

In [6]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


##### Explicitly pass the data type

In [7]:
arr = np.array([12, 43, 15], dtype=np.float64)
arr

array([12., 43., 15.])

### Create arrays of known size

##### Populate array with zeros

In [8]:
arr = np.zeros((3, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##### Populate array with ones

In [9]:
arr = np.ones((6))
arr

array([1., 1., 1., 1., 1., 1.])

##### Populate array with random numbers

In [10]:
arr = np.empty((2, 3, 2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

##### Explicitly pass the data type

In [11]:
arr = np.zeros((1, 2), dtype=np.int32)
arr

array([[0, 0]])

### Create array with sequence of numbers

In [12]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [13]:
arr = np.arange(10, 16)
arr

array([10, 11, 12, 13, 14, 15])

##### Populate array with evenly spaced numbers

In [14]:
arr = np.arange(1, 25, 3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22])

##### Get an evenly-spaced array with floating point numbers

In [15]:
arr = np.linspace(10, 20, 5)
arr

array([10. , 12.5, 15. , 17.5, 20. ])

## Basic array attributes

In [16]:
arr = np.zeros((4, 5))

##### Number of dimensions

In [17]:
arr.ndim

2

##### Shape

In [18]:
arr.shape

(4, 5)

##### Size

In [19]:
arr.size

20

##### Data type

In [20]:
arr.dtype

dtype('float64')

##### Item size

In [21]:
arr.itemsize

8

## Broadcasting

In [22]:
a = np.array([[1, 2], [3, 4]])
b = 5

In [23]:
a*b

array([[ 5, 10],
       [15, 20]])

## Change shape of an array

In [24]:
arr = np.arange(20)
arr.shape

(20,)

##### Reshape

In [25]:
reshaped = arr.reshape((4, 5))
reshaped.shape

(4, 5)

In [26]:
#Leave one dimension to be automatically calculated
reshaped_auto = arr.reshape((5, -1))
reshaped_auto.shape

(5, 4)

##### Flatten & unravel

In [28]:
flattened = reshaped.flatten()
print(flattened.shape)

flattened[0] = 50

print("Parent array", reshaped)
print("Flattened array", flattened)

(20,)
Parent array [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Flattened array [50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
unravelled = reshaped.ravel()
print(unravelled.shape)

unravelled[0] = 50

print("Parent array", reshaped)
print("Unravelled array", unravelled)

(20,)
Parent array [[50  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Unravelled array [50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


##### Resize

In [31]:
arr = np.arange(20)
arr.resize((2, 10))
arr.shape

(2, 10)

## Indexing & slicing

##### One-dimensional arrays

In [32]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr[5]

5

In [34]:
arr[-1]

14

In [35]:
arr[7] = 100
arr[7]

100

In [36]:
#Slice the elements between indices 2 and 7
arr[2:7]

array([2, 3, 4, 5, 6])

In [37]:
#Choose every 3rd element between the indices 0 and 10
arr[:10:3]

array([0, 3, 6, 9])

In [38]:
#Reverse the entire array
arr[::-1]

array([ 14,  13,  12,  11,  10,   9,   8, 100,   6,   5,   4,   3,   2,
         1,   0])

##### Multi-dimensional arrays

In [39]:
arr = np.arange(18).reshape(3, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [40]:
arr[1, 4]

10

In [41]:
arr[-1, 4]

16

In [42]:
#Slice columns 2 to 4 of each row of the array
arr[:, 1:4]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [43]:
#1st, 3rd, 5th elements of the 2nd row of the array
arr[1, 0:6:2]

array([ 6,  8, 10])

In [44]:
#Slice the last column of the array
arr[:, -1]

array([ 5, 11, 17])

##### Filter elements using special conditions

In [45]:
arr[arr < 5]

array([0, 1, 2, 3, 4])

In [46]:
arr[arr % 4 == 0]

array([ 0,  4,  8, 12, 16])

In [47]:
arr[(arr > 3) & (arr < 12)]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## Basic operations

In [48]:
a = np.arange(1, 7).reshape((2, 3))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
b = np.array([[12, 32, 21], [99, 34, 43]])
b

array([[12, 32, 21],
       [99, 34, 43]])

##### Multiply by a constant

In [50]:
a*5

array([[ 5, 10, 15],
       [20, 25, 30]])

##### Summation

In [51]:
a + b

array([[ 13,  34,  24],
       [103,  39,  49]])

##### Substraction

In [52]:
a - b

array([[-11, -30, -18],
       [-95, -29, -37]])

##### Power

In [53]:
a**3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

##### Element-wise multiplication

In [54]:
a * b

array([[ 12,  64,  63],
       [396, 170, 258]])

##### Element-wise division

In [55]:
b / a

array([[12.        , 16.        ,  7.        ],
       [24.75      ,  6.8       ,  7.16666667]])

##### Sum, min, and max

In [56]:
a.sum()

21

In [57]:
b.min()

12

In [58]:
b.max()

99

In [59]:
#Maximum in each column
b.max(axis=0)

array([99, 34, 43])

In [60]:
#Minimum in each row
b.min(axis=1)

array([12, 34])

##### Mean, median, and sort

In [61]:
np.mean(b)

40.166666666666664

In [62]:
np.median(b)

33.0

In [63]:
np.median(b, axis=1)

array([21., 43.])

In [64]:
np.sort(b)

array([[12, 21, 32],
       [34, 43, 99]])

## Matrix operations

In [65]:
a = np.arange(6).reshape((2, 3))
b = np.arange(9).reshape((3, 3))

##### Matrix multiplication (dot product)

In [66]:
a @ b

array([[15, 18, 21],
       [42, 54, 66]])

In [67]:
a.dot(b)

array([[15, 18, 21],
       [42, 54, 66]])

##### Transposing a matrix

In [68]:
transposed = a.transpose()
transposed.shape

(3, 2)

##### Get the determinant

In [69]:
determinant = np.linalg.det(b)
determinant

0.0

## Stacking & splitting arrays

In [70]:
a = np.linspace(1, 50, 8).reshape(2, 4)
b = np.arange(4).reshape(2, 2)
c = np.arange(12).reshape(3, 4)

##### Horizontal stack

In [71]:
np.hstack((a, b))

array([[ 1.,  8., 15., 22.,  0.,  1.],
       [29., 36., 43., 50.,  2.,  3.]])

##### Vertical stack

In [72]:
np.vstack((a, c))

array([[ 1.,  8., 15., 22.],
       [29., 36., 43., 50.],
       [ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

##### Horizontal split

In [73]:
#Split into two equal-sized arrays
split_a = np.hsplit(a, 2)

print(split_a[0])
print(split_a[1])

[[ 1.  8.]
 [29. 36.]]
[[15. 22.]
 [43. 50.]]


In [74]:
#Split the array after the 1st and 3rd columns
split_a = np.hsplit(a, (1, 3))

print(split_a[0])
print(split_a[1])
print(split_a[2])

[[ 1.]
 [29.]]
[[ 8. 15.]
 [36. 43.]]
[[22.]
 [50.]]


##### Vertical split

In [75]:
#Split into three equal-sized arrays
split_c = np.vsplit(c, 3)

print(split_c[0])
print(split_c[1])
print(split_c[2])

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


In [76]:
#Split the array after the 1st row

split_c = np.vsplit(c, (1, ))

print(split_c[0])
print(split_c[1])

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]


## Deep & shallow copies

In [77]:
a = np.arange(10)

##### Shallow copy

In [78]:
b = a.view()

In [79]:
b is a

False

In [80]:
b.reshape(2, 5)
a.shape

(10,)

In [81]:
b[8] = 99
a[8]

99

##### Deep copy

In [82]:
c = a.copy()

In [83]:
c is a

False

In [84]:
c.reshape(2, 5)
a.shape

(10,)

In [85]:
c[5] = 55
a[5]

5

## Import & export data

##### Import data

In [86]:
import pandas as pd

In [87]:
df = pd.read_csv("drinks.csv")
df.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF

In [88]:
arr = df["wine_servings"].to_numpy()
arr.shape

(193,)

##### Export data

In [89]:
df = pd.DataFrame(arr)
df.to_csv("wine_servings.csv")